In [1]:
from auth import *
from cross_validation import cross_val_score
from BayesClassifier import *
from KNN import *
import pandas as pd

In [2]:
df = pd.read_csv("data/basis_learning/tweets_clean_annoted.csv",index_col=0)

In [3]:
X, y = df['tweet'].values, df['polarity'].values

In [35]:
labels = ['Présence, uni-gramme', 'Présence, bi-gramme',
         'Présence, uni-gramme + bi-gramme',
         'Fréquence, uni-gramme','Fréquence, bi-gramme',
         'Fréquence, uni-gramme + bi-gramme']

In [28]:
models = [BayesClassifier(freq=False,n_gram=1), 
          BayesClassifier(freq=False,n_gram=2),
          BayesClassifier(freq=False,n_gram=2,combinaison=True),
          BayesClassifier(freq=True,n_gram=1),
          BayesClassifier(freq=True,n_gram=2),
          BayesClassifier(freq=True,n_gram=2,combinaison=True)]

In [31]:
scores = np.array([cross_val_score(X,y,10,m) for m in models])

In [37]:
labels[scores.argmax()], scores[scores.argmax()]

('Présence, uni-gramme', 0.647020974049058)

In [38]:
cross_val_score(X,y,10,KNN())

0.7938535371489512

In [58]:
client = authpy()
new_tweets = pd.DataFrame(client.search_recent_tweets(query="famille addams",tweet_fields=['context_annotations'], max_results=100)[0])['text']

In [67]:
X_test = new_tweets.values
X_test

array(['@FBeuvelet @laurentwauquiez @BrunoRetailleau @ECiotti @AurelienPradie La famille Addams.',
       "RT @NetflixFR: La Chose in Paris : un 𝘮𝘦𝘮𝘣𝘳𝘦 de la famille Addams était présent hier à l'avant-première d'Emily in Paris ! https://t.co/i3C…",
       '🧠 : let\'s go 😁 *passe le générique de la famille Addams"',
       "j'ai commencé Wednesday (j'ai jamais vu La Famille Addams par contre)",
       "@KotamiKumagawa T'a déjà vu la famille Addams ?\nY'a 2-3 réf mais la mentalité est pas respecté la",
       "L'écriture c'est les montagnes russe, c'est super bien d'un côté (la partie meurtres enquêtes etc) mais la partie DANS Nevermore et du côté de la Famille Addams y'a un réel soucis. Mercredi est bien traitée mais on la colle dans un triangle amoureux alors que ça l'intéresse pas.",
       "Bon alors déjà y'a un énorme problème de relation entre Morticia et Mercredi, c'est clairement pas du tout tiré de la Famille Addams, mais qui est le débile de scénariste qui a foutu un triangle 

In [64]:
clf = KNN().fit(X,y)

In [69]:
y_pred = clf.predict(X_test)

In [70]:
y_pred

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 4,
       2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [79]:
np.unique(y_pred,return_counts=True)

(array([2, 4], dtype=int64), array([90,  9], dtype=int64))

In [73]:
blf = BayesClassifier(freq=False,n_gram=1)
blf.fit(X,y)

In [76]:
y_pred_blf = blf.predict(X_test)
y_pred_blf

array([2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2,
       2, 2, 2, 2, 2, 4, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 2, 4, 2, 4, 4, 4,
       4, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 2, 2, 2, 2, 4, 2, 4, 2, 2, 2, 4,
       2, 2, 2, 2, 2, 0, 4, 2, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 2, 2, 2, 4,
       2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 2], dtype=int64)

In [78]:
np.unique(blf.predict(X_test),return_counts=True)

(array([0, 2, 4], dtype=int64), array([ 1, 65, 33], dtype=int64))